"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Contractor={id:string;name:string;trade:string;email:string;phone:string;coverage:string;status:string;notes:string;document_count:number;expired_count:number};
type Document={id:string;contractor_id:string;document_type:string;file_name:string;expiry_date:string;uploaded_at:number};
const trades=["All trades","Asbestos","Building & general works","Electrical","Fire alarms","Fire doors","Gas","Grounds maintenance","HVAC","Lifts","Plumbing & drainage","Roofing","Security","Smoke control","Water hygiene"];
const documentTypes=["Public liability insurance","Employers’ liability insurance","Professional indemnity insurance","SSIP / CHAS / SafeContractor","Trade accreditation","Health & safety policy","RAMS","Waste carrier licence","DBS / safeguarding","Other compliance document"];
const empty={name:"",trade:"Fire alarms",email:"",phone:"",coverage:"",status:"Approved",notes:""};

function docStatus(expiry:string){if(!expiry)return "no-expiry";const days=Math.ceil((new Date(expiry+"T23:59:59").getTime()-Date.now())/86400000);return days<0?"expired":days<=30?"due":"current"}
export default function Contractors(){
 const[contractors,setContractors]=useState<Contractor[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[trade,setTrade]=useState("All trades"),[adding,setAdding]=useState(false),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Contractor|null>(null),[documents,setDocuments]=useState<Document[]>([]),[docType,setDocType]=useState(documentTypes[0]),[expiry,setExpiry]=useState(""),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/contractors");setContractors(r.ok?await r.json():[])}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function loadDocuments(id:string){const r=await fetch(`/api/contractors/${id}/documents`);setDocuments(r.ok?await r.json():[])}
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/contractors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),body=await r.json() as {error?:string};setBusy(false);if(!r.ok){setMessage(body.error||"Contractor could not be added");return}setAdding(false);setForm(empty);setMessage("Approved contractor added.");await load()}
 async function upload(file?:File){if(!file||!selected)return;setBusy(true);setMessage("");const data=new FormData();data.set("file",file);data.set("documentType",docType);data.set("expiryDate",expiry);const r=await fetch(`/api/contractors/${selected.id}/documents`,{method:"POST",body:data}),body=await r.json() as {error?:string};setBusy(false);if(!r.ok){setMessage(body.error||"Document could not be uploaded");return}setExpiry("");setMessage(`${docType} saved against ${selected.name}.`);await Promise.all([loadDocuments(selected.id),load()])}
 const filtered=useMemo(()=>contractors.filter(c=>(trade==="All trades"||c.trade===trade)&&`${c.name} ${c.trade} ${c.email} ${c.coverage}`.toLowerCase().includes(search.toLowerCase())),[contractors,search,trade]);
 const approved=contractors.filter(c=>c.status==="Approved").length,attention=contractors.filter(c=>Number(c.expired_count)>0).length;
 function open(c:Contractor){setSelected(c);setMessage("");void loadDocuments(c.id)}
 return <><div className="contractor-head"><div><p className="eyebrow">SUPPLIER & CONTRACTOR CONTROL</p><h1>Approved contractors</h1><p>Search approved firms by trade and keep their insurance, accreditation and compliance certificates together.</p></div><button className="primary" onClick={()=>setAdding(true)}>＋ Add contractor</button></div><section className="stat-grid three contractor-stats"><article className="stat green"><div><span>Approved contractors</span><strong>{approved}</strong><small>Available across the portfolio</small></div><i>✓</i></article><article className="stat blue"><div><span>Trades covered</span><strong>{new Set(contractors.map(c=>c.trade)).size}</strong><small>Approved specialisms</small></div><i>⌁</i></article><article className="stat amber"><div><span>Documents requiring attention</span><strong>{attention}</strong><small>Contractors with expired records</small></div><i>!</i></article></section>{message&&<p className="contractor-message" role="status">{message}</p>}<section className="contractor-directory"><div className="contractor-tools"><label className="contractor-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search contractor, trade, email or area…"/></label><label>Trade<select value={trade} onChange={e=>setTrade(e.target.value)}>{trades.map(t=><option key={t}>{t}</option>)}</select></label></div>{loading?<div className="contractor-empty">Loading approved contractors…</div>:filtered.length?<div className="contractor-table"><div className="contractor-table-head"><span>Contractor</span><span>Trade</span><span>Coverage</span><span>Documents</span><span>Status</span><span/></div>{filtered.map(c=><button className="contractor-row" key={c.id} onClick={()=>open(c)}><span className="contractor-name"><i>{c.name.slice(0,2).toUpperCase()}</i><span><b>{c.name}</b><small>{c.email}{c.phone?` · ${c.phone}`:""}</small></span></span><span>{c.trade}</span><span>{c.coverage||"Not specified"}</span><span><b>{Number(c.document_count)||0}</b> records</span><span><em className={Number(c.expired_count)>0?"attention":"approved"}>{Number(c.expired_count)>0?"Attention":"Approved"}</em></span><span>›</span></button>)}</div>:<div className="contractor-empty"><span>⌁</span><h2>{contractors.length?"No contractors match your search":"No approved contractors yet"}</h2><p>{contractors.length?"Try another trade or search term.":"Add your first approved contractor and upload their compliance certificates."}</p>{!contractors.length&&<button className="primary" onClick={()=>setAdding(true)}>＋ Add contractor</button>}</div>}</section>
 {adding&&<div className="contractor-modal" onClick={()=>setAdding(false)}><form onSubmit={create} onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">APPROVED SUPPLIER</p><h2>Add contractor</h2></div><button type="button" onClick={()=>setAdding(false)}>×</button></header><label>Company name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="contractor-two"><label>Primary trade<select value={form.trade} onChange={e=>setForm({...form,trade:e.target.value})}>{trades.slice(1).map(t=><option key={t}>{t}</option>)}</select></label><label>Approval status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Approved</option><option>Pending review</option><option>Suspended</option></select></label></div><div className="contractor-two"><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><label>Coverage area<input value={form.coverage} onChange={e=>setForm({...form,coverage:e.target.value})} placeholder="e.g. London and South East"/></label><label>Notes<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><footer><button type="button" className="outline" onClick={()=>setAdding(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Add approved contractor"}</button></footer></form></div>}
 {selected&&<div className="contractor-modal" onClick={()=>setSelected(null)}><section className="contractor-detail" onClick={e=>e.stopPropagation()}><header><div className="contractor-profile"><i>{selected.name.slice(0,2).toUpperCase()}</i><div><p className="eyebrow">{selected.trade.toUpperCase()}</p><h2>{selected.name}</h2><span>{selected.email}{selected.phone?` · ${selected.phone}`:""}</span></div></div><button onClick={()=>setSelected(null)}>×</button></header><div className="contractor-facts"><span>Approval<b>{selected.status}</b></span><span>Coverage<b>{selected.coverage||"Not specified"}</b></span><span>Compliance records<b>{documents.length}</b></span></div><div className="document-upload"><div><h3>Upload compliance certificate</h3><p>Choose the record type and expiry date before uploading.</p></div><div className="document-upload-fields"><label>Document type<select value={docType} onChange={e=>setDocType(e.target.value)}>{documentTypes.map(d=><option key={d}>{d}</option>)}</select></label><label>Expiry date<input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label className={busy?"busy":""}>↑ {busy?"Uploading…":"Choose document"}<input hidden type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" disabled={busy} onChange={e=>{void upload(e.currentTarget.files?.[0]);e.currentTarget.value=""}}/></label></div></div><div className="document-list-head"><div><h3>Compliance documents</h3><p>Insurance, accreditation and safety records for this contractor.</p></div><span>{documents.length} documents</span></div><div className="contractor-documents">{documents.length?documents.map(d=>{const status=docStatus(d.expiry_date);return <a key={d.id} href={`/api/contractors/${selected.id}/documents?file=${encodeURIComponent(d.id)}`} target="_blank"><i>▤</i><span><b>{d.document_type}</b><small>{d.file_name} · Uploaded {new Date(d.uploaded_at).toLocaleDateString("en-GB")}</small></span><em className={status}>{status==="expired"?"Expired":status==="due"?"Due soon":status==="current"?`Expires ${new Date(d.expiry_date).toLocaleDateString("en-GB")}`:"No expiry"}</em><strong>Open</strong></a>}):<div className="documents-empty">No compliance documents uploaded yet.</div>}</div></section></div>}
 </>
}
