"use client";
import { useMemo, useState } from "react";

type View="overview"|"buildings"|"golden"|"maintenance"|"residents"|"finance"|"messages";
const nav:[View,string,string][]=[["overview","Portfolio overview","⌂"],["buildings","Buildings","▦"],["golden","Building safety","◇"],["maintenance","Maintenance","⌁"],["residents","Residents","◎"],["finance","Service charges","£"],["messages","Communications","□"]];
const golden=[["Building registration","HRB registration, key building information and accountable persons","12","Current"],["Safety case","Safety case report, evidence and BSR correspondence","18","Review due"],["Fire safety","Fire strategy, FRA, compartmentation, doors, alarms and smoke control","34","2 actions"],["Structural safety","Structural assessments, load limits, monitoring and remedial works","11","Current"],["Plans & drawings","As-built plans, floor layouts, fire compartments and service routes","27","Current"],["Maintenance & inspections","Planned maintenance, statutory inspections and test certificates","46","4 due"],["Changes & refurbishments","Change control, approvals, gateways, competence and handover","9","Current"],["Mandatory occurrences","Occurrence notices, BSR reports, investigations and corrective actions","3","1 open"],["Incidents & emergencies","Incidents, near misses, emergency plans and fire service information","15","Current"],["Resident engagement","Engagement strategy, consultations, PEEPs and safety communications","21","Current"],["Complaints & concerns","Safety complaints, investigations, escalation and closure","6","1 open"],["Audit & assurance","Audits, regulator inspections, non-conformances and actions","19","3 actions"]];
const tickets=[["MA-1048","Water ingress · Flat 8.14","Riverside Point","Urgent","Assigned"],["MA-1047","Lift 2 intermittent fault","The Foundry","High","Contractor attending"],["MA-1046","Communal lighting · Level 4","Riverside Point","Medium","New"],["MA-1045","Entrance door closer","Ashcroft House","Medium","Awaiting parts"]];

export default function Home(){const[view,setView]=useState<View>("overview");const[mobile,setMobile]=useState(false);const[query,setQuery]=useState("");const today=useMemo(()=>new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date()),[]);return <main className="app-shell">
 <aside className={`sidebar ${mobile?"open":""}`}><div className="brand"><div><strong>Managing Agent Portal</strong><span>Property management</span></div></div><button className="close-nav" onClick={()=>setMobile(false)}>×</button><div className="portfolio-switch"><span>PORTFOLIO</span><button>UK Residential <b>⌄</b></button></div><nav>{nav.map(n=><button key={n[0]} className={view===n[0]?"active":""} onClick={()=>{setView(n[0]);setMobile(false)}}><i>{n[2]}</i>{n[1]}{n[0]==="golden"&&<em>7</em>}</button>)}</nav><div className="side-footer"><div className="help-card"><b>Need support?</b><span>Property operations team</span><button>Contact support</button></div><div className="user"><span>BK</span><div><b>Brian Klue</b><small>Portfolio manager</small></div><button>•••</button></div></div></aside>
 <section className="workspace"><header><button className="menu" onClick={()=>setMobile(true)}>☰</button><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search buildings, residents, documents…"/></div><div className="header-actions"><button>♢<i>4</i></button><button className="primary">＋ Create</button></div></header><div className="content">{view==="overview"&&<Overview today={today} go={setView}/>} {view==="golden"&&<Golden query={query}/>} {view==="maintenance"&&<Maintenance/>} {!(["overview","golden","maintenance"] as string[]).includes(view)&&<Placeholder view={view}/>}</div></section>
 </main>}

function Overview({today,go}:{today:string;go:(v:View)=>void}){return <><PageHead eyebrow="PORTFOLIO COMMAND CENTRE" title="Good morning, Brian" sub={`${today} · 8 managed buildings`} action="Download portfolio report"/><section className="stat-grid"><Stat l="Homes managed" v="486" n="Across 8 buildings" t="blue"/><Stat l="Open maintenance" v="18" n="3 require attention" t="amber"/><Stat l="Compliance" v="94%" n="7 actions outstanding" t="green"/><Stat l="Service charge arrears" v="£42.8k" n="4.1% of demands" t="red"/></section><section className="overview-grid"><div className="panel"><PanelHead eye="PRIORITIES" title="Action centre" action="View all"/><Action c="red" title="2 fire-door inspections overdue" meta="Riverside Point · Due 21 Aug" tag="Critical" go={()=>go("golden")}/><Action c="amber" title="Safety Case Report review" meta="The Foundry · Due in 6 days" tag="Due soon" go={()=>go("golden")}/><Action c="blue" title="3 maintenance requests unassigned" meta="Across 2 buildings" tag="New" go={()=>go("maintenance")}/><Action c="violet" title="Resident consultation awaiting issue" meta="Ashcroft House · Balcony works" tag="Draft" go={()=>go("messages")}/></div><div className="panel"><PanelHead eye="BUILDING SAFETY" title="Compliance health" action="Open safety centre"/><div className="donut-wrap"><div className="donut"><strong>94%</strong><span>compliant</span></div><div className="legend"><p><i className="g"/>Current <b>131</b></p><p><i className="a"/>Due soon <b>9</b></p><p><i className="r"/>Overdue <b>3</b></p></div></div><div className="next-review"><span>Next statutory review</span><b>Fire risk assessment</b><small>Riverside Point · 29 August 2026</small></div></div></section><section className="panel building-panel"><PanelHead eye="YOUR PORTFOLIO" title="Buildings at a glance" action="View all buildings"/><Building initials="RP" name="Riverside Point" detail="London SE1 · 112 homes · Higher-risk building" score="91%" jobs="7" arrears="£14.2k"/><Building initials="TF" name="The Foundry" detail="Manchester M3 · 86 homes · Higher-risk building" score="96%" jobs="4" arrears="£8.6k"/></section></>}
function PageHead({eyebrow,title,sub,action}:{eyebrow:string,title:string,sub:string,action:string}){return <div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{sub}</p></div><button className={action.startsWith("Download")?"outline":"primary"}>{action}</button></div>}
function PanelHead({eye,title,action}:{eye:string,title:string,action:string}){return <div className="panel-head"><div><p className="eyebrow">{eye}</p><h2>{title}</h2></div><button>{action}</button></div>}
function Stat({l,v,n,t}:{l:string;v:string;n:string;t:string}){return <article className={`stat ${t}`}><div><span>{l}</span><strong>{v}</strong><small>{n}</small></div><i>{t==="green"?"✓":t==="amber"?"!":t==="red"?"↗":"▦"}</i></article>}
function Action({c,title,meta,tag,go}:{c:string;title:string;meta:string;tag:string;go:()=>void}){return <button className="action" onClick={go}><i className={c}/><div><b>{title}</b><span>{meta}</span></div><em className={c}>{tag}</em><strong>›</strong></button>}
function Building(p:{initials:string;name:string;detail:string;score:string;jobs:string;arrears:string}){return <div className="building-row"><div className="building-image">{p.initials}</div><div><b>{p.name}</b><span>{p.detail}</span></div><div className="meter"><span>Compliance</span><b>{p.score}</b><i><em style={{width:p.score}}/></i></div><div className="row-metric"><span>Open jobs</span><b>{p.jobs}</b></div><div className="row-metric"><span>Arrears</span><b>{p.arrears}</b></div><button>→</button></div>}

function Golden({query}:{query:string}){const[tab,setTab]=useState("library");const sections=golden.filter(x=>(x[0]+x[1]).toLowerCase().includes(query.toLowerCase()));return <><PageHead eyebrow="RIVERSIDE POINT · HRB-10482" title="Building Safety & Golden Thread" sub="One controlled record for building safety, compliance and resident assurance." action="＋ Add record"/><div className="safety-banner"><div><span>◇</span><div><b>Safety case health</b><strong>Substantial assurance</strong></div></div><p><b>7</b> open actions</p><p><b>2</b> reviews due</p><p><b>94%</b> records current</p><button>View safety case →</button></div><div className="tabs"><button className={tab==="library"?"active":""} onClick={()=>setTab("library")}>Golden Thread</button><button className={tab==="actions"?"active":""} onClick={()=>setTab("actions")}>Action register <i>7</i></button><button className={tab==="mor"?"active":""} onClick={()=>setTab("mor")}>Occurrence reporting</button><button className={tab==="residents"?"active":""} onClick={()=>setTab("residents")}>Resident engagement</button></div>{tab==="library"?<><div className="section-tools"><div><h2>Controlled information library</h2><p>Documents, evidence and records throughout the building lifecycle.</p></div><div><button>☷ Filter</button><button>⇩ Export index</button></div></div><div className="golden-grid">{sections.map((s,i)=><article className="gold-card" key={s[0]}><div className={`gold-icon i${i%4}`}>{["▦","◇","♢","△"][i%4]}</div><div className="gold-copy"><h3>{s[0]}</h3><p>{s[1]}</p><div><span>{s[2]} records</span><em className={s[3].includes("Current")?"ok":"warn"}>{s[3]}</em></div></div><button>→</button></article>)}</div></>:<Feature title={tab==="actions"?"Building safety action register":tab==="mor"?"Mandatory occurrence reporting":"Resident engagement"} text={tab==="actions"?"Track ownership, priority, target dates, evidence and verified closure.":tab==="mor"?"Assess reportability and retain BSR notices, reports and investigations.":"Manage the engagement strategy, consultations, safety notices and feedback."}/>}</>}
function Maintenance(){return <><PageHead eyebrow="OPERATIONS" title="Maintenance" sub="Report, triage and track work from first contact to resident sign-off." action="＋ New work order"/><section className="stat-grid three"><Stat l="Open requests" v="18" n="Across 6 buildings" t="blue"/><Stat l="Urgent" v="3" n="Within SLA response" t="red"/><Stat l="Completed this month" v="42" n="92% within target" t="green"/></section><div className="panel table-panel"><PanelHead eye="LIVE WORK" title="Requests and work orders" action="Filter & sort"/><div className="ticket-table"><div className="table-header"><span>Reference</span><span>Request</span><span>Building</span><span>Priority</span><span>Status</span></div>{tickets.map(t=><button className="ticket" key={t[0]}>{t.map((v,i)=><span key={v} className={i===3?`priority ${v.toLowerCase()}`:i===4?"status":""}>{v}</span>)}<b>›</b></button>)}</div></div></>}
function Feature({title,text}:{title:string;text:string}){return <div className="feature-panel"><span>◇</span><h2>{title}</h2><p>{text}</p><button className="primary">＋ Create first record</button></div>}
function Placeholder({view}:{view:View}){const labels:Record<string,string>={buildings:"Buildings & estates",residents:"Residents & leaseholders",finance:"Service charges & arrears",messages:"Communications"};return <><PageHead eyebrow="MANAGEMENT" title={labels[view]} sub="A connected workspace for every building, resident and management task." action="＋ Create"/><Feature title={`${labels[view]} workspace`} text="This module is included in the portal structure and ready for the next workflow layer."/></>}
