"use client";
import {useEffect,useMemo,useState} from "react";
type Order={id:string;reference:string;title:string;building:string;contractor:string;contractor_email:string;priority:string;status:string;description:string;due_date:string;invoice_name?:string;invoice_status:string};
type ApprovedContractor={id:string;name:string;trade:string;email:string;phone:string;coverage:string;status:string;document_count:number;expired_count:number};
const empty={title:"",building:"Riverside Point",contractor_id:"",priority:"Medium",description:"",due_date:""};
export default function WorkOrders(){
 const[orders,setOrders]=useState<Order[]>([]),[contractors,setContractors]=useState<ApprovedContractor[]>([]),[creating,setCreating]=useState(false),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const[work,approved]=await Promise.all([fetch("/api/work-orders"),fetch("/api/contractors")]);if(work.ok)setOrders(await work.json());if(approved.ok){const rows=await approved.json() as ApprovedContractor[];setContractors(rows.filter(c=>c.status==="Approved"))}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(contractors.length&&!form.contractor_id)setForm(x=>({...x,contractor_id:contractors[0].id}))},[contractors,form.contractor_id]);
 const selected=useMemo(()=>contractors.find(c=>c.id===form.contractor_id),[contractors,form.contractor_id]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/work-orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),body=await r.json() as {error?:string;reference?:string};setBusy(false);if(!r.ok){setMessage(body.error||"Work order could not be issued");return}setCreating(false);setForm({...empty,contractor_id:contractors[0]?.id||""});setMessage(`${body.reference} issued to an approved contractor.`);void load()}
 async function invoice(id:string,file?:File){if(!file)return;const data=new FormData();data.append("invoice",file);await fetch(`/api/work-orders/${id}/invoice`,{method:"POST",body:data});void load()}
 return <><div className="work-head"><div><p className="eyebrow">CONTRACTOR MANAGEMENT</p><h1>Work orders</h1><p>Issue jobs only to approved contractors and keep invoices against the correct work-order reference.</p></div><button className="primary" onClick={()=>setCreating(true)}>＋ New work order</button></div><section className="stat-grid three"><article className="stat blue"><div><span>Open work orders</span><strong>{orders.filter(o=>o.status!=="Completed").length}</strong><small>Live contractor jobs</small></div><i>⌁</i></article><article className="stat amber"><div><span>Awaiting invoices</span><strong>{orders.filter(o=>!o.invoice_name).length}</strong><small>Invoice still required</small></div><i>£</i></article><article className="stat green"><div><span>Approved contractors</span><strong>{contractors.length}</strong><small>Available for new work orders</small></div><i>✓</i></article></section>{message&&<p className="work-message" role="status">{message}</p>}<div className="approved-only-note"><span>✓</span><div><b>Approved contractors only</b><p>New work orders are connected to the contractor register. Pending, suspended or unregistered firms cannot be selected.</p></div></div>
 <div className="work-list">{orders.length?orders.map(o=><article className="work-order" key={o.id}><header><div><span>{o.reference}</span><h3>{o.title}</h3><p>{o.building} · {o.contractor}</p></div><em className={o.priority.toLowerCase()}>{o.priority}</em></header><div className="work-meta"><span>Status<b>{o.status}</b></span><span>Due date<b>{o.due_date||"Not set"}</b></span><span>Invoice<b>{o.invoice_status}</b></span></div>{o.invoice_name?<div className="invoice-received"><span>▤</span><div><b>{o.invoice_name}</b><small>Invoice attached to {o.reference}</small></div></div>:<label className="invoice-upload">↑ Contractor upload invoice<input hidden type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={e=>invoice(o.id,e.target.files?.[0])}/></label>}</article>):<div className="work-empty"><span>⌁</span><h2>No work orders yet</h2><p>Create the first order and issue it to an approved contractor.</p><button className="primary" onClick={()=>setCreating(true)}>＋ New work order</button></div>}</div>
 {creating&&<div className="folder-dialog-backdrop" onClick={()=>setCreating(false)}><form className="work-form" onSubmit={create} onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">NEW APPROVED-CONTRACTOR JOB</p><h2>Create work order</h2></div><button type="button" onClick={()=>setCreating(false)}>×</button></header>{message&&<p className="work-form-error">{message}</p>}<label>Job title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-two"><label>Building<select value={form.building} onChange={e=>setForm({...form,building:e.target.value})}>{["Riverside Point","The Foundry","Ashcroft House","Harbour View"].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label></div><label>Approved contractor<select required value={form.contractor_id} disabled={!contractors.length} onChange={e=>setForm({...form,contractor_id:e.target.value})}>{contractors.length?contractors.map(c=><option value={c.id} key={c.id}>{c.name} — {c.trade}</option>):<option value="">No approved contractors available</option>}</select></label>{selected?<div className="selected-contractor"><span>{selected.name.slice(0,2).toUpperCase()}</span><div><b>{selected.name}</b><p>{selected.trade} · {selected.email}</p><small>{selected.coverage||"Coverage not specified"}</small></div><em className={Number(selected.expired_count)>0?"warning":"ok"}>{Number(selected.expired_count)>0?"Compliance attention":"Approved"}</em></div>:<div className="no-approved"><b>No approved contractor available</b><span>Add and approve the contractor in the Contractors section before issuing this work order.</span></div>}<label>Required by<input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label>Description<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><footer><button type="button" className="outline" onClick={()=>setCreating(false)}>Cancel</button><button className="primary" disabled={busy||!selected}>{busy?"Issuing…":"Issue to approved contractor"}</button></footer></form></div>}</>}
